### PR TITLE
Charles/move to tab

### PR DESCRIPTION
**Pull request by charlesx2013**
We now use tabs instead of the navbar!

@kelseylam 

screenshot_20151224-190029

### CODE REVIEW

**Comment by amillman** [comment]
ey......no one gave you permission to merge

**Comment by amillman** [comment]
you should make the tab icons match the icons for ios @charlesx2013 . also in regards to not putting the title in the navbar, after looking at it a bit i think its kinda weird that theres no title for each tab. yea, after a couple of uses people will realize "oh, this is the anonouncements tab" or whatever. but apps like tumblr can get away with this because they have a huge and already dedicated user base that use their app everyday. these people are gonna be using this app probably once a week, so its pretty easy for them to forget almost every time until the end of the semester when they start familiarizing which icon is which tab, but then break comes. we dont really have the luxury that tumblr has. i think either having labels right below or above each icon (which you can do using a custom view http://www.androidhive.info/2015/09/android-material-design-working-with-tabs/) will probably be better. please at least unify tha icons tho

**Comment by charlesx2013** [comment]
:P I merge myself now. I mean icons wise i can change. (psst google icons > whatever you guys have). But in terms of tabs. There are literally four tabs. 3 even, if you're just a student. I think it's ok to not have labels on them.

**Comment by amillman** [comment]
oh also put check in in the middle

**Pull request merged**
